module DefenceType

	BASE_SOAK = :base
	BONUS_SOAK = :bonus

	APPLICATION = [BASE_SOAK, BONUS_SOAK]

	CLOSE_COMBAT_AVOIDANCE = :close
	RANGED_COMBAT_AVOIDANCE = :ranged
	GENERIC_COMBAT_AVOIDANCE = :generic

	AVOIDANCE = [CLOSE_COMBAT_AVOIDANCE, RANGED_COMBAT_AVOIDANCE, GENERIC_COMBAT_AVOIDANCE]
end