---
engines:
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- config/
- features/
- public/icons/
- public/images/
- public/img/
- public/swf/
- public/tiles/
- public/ails/
- public/css/images/
- public/css/jqui/
- public/css/sass/
- "public/js/*jquery*.js"
- "public/css/*dataTables*.css"
- "public/js/*dataTables*.js"
- "public/css/*jquery*.css"
- "public/css/absolution*.css"
- "public/js/dataTables.tableTools.js"
- "public/js/dataTables.tableTools.js"
- "public/js/dataTables.tableTools.min.js"
- "public/js/jquery-1.10.2_min.js"
- "public/js/jquery-migrate.min.js"
- "public/js/jquery-ui-1.10.3.custom.js"
- "public/js/jquery-ui-1.10.3.custom.min.js"
- "public/js/jquery.dataTables.js"
- "public/js/jquery.dataTables.min.js"
- "public/js/jquery.js"