source 'https://rubygems.org'

gem 'sinatra'
gem 'haml'
gem 'require_all'
gem 'sinatra-session'
gem 'thread_safe'
gem 'rufus-scheduler'
gem 'eventmachine'
gem 'faye-websocket'
gem 'websocket-extensions'
gem 'permessage_deflate'
gem 'puma'
gem 'mongoid'
gem 'opal'
#gem 'opal-jquery'
gem 'opal-browser', '~> 0.2.0.beta1'
gem 'unobservable'
gem 'mongoid-autoinc'